### ISSUE TITLE
依赖失败了

### ISSUE THREAD

**Issue by zhangruiyu** [Vanish136/StateFrameLayout#1]
implementation 'com.lwkandroid.widget:StateFrameLayout:1.1.0'

**Comment by zhangruiyu** [comment]
mavenCentral()
        maven { url "https://jitpack.io" }
        jcenter()
        google()
        maven { url "http://maven.aliyun.com/nexus/content/groups/public/" }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }

**Comment by LwkCoder** [comment]
@zhangruiyu 谢谢反馈，我检查了下代码确实有传到maven上去，但是jcenter那边却没有，暂时没找到原因，你要着急可以直接把库clone下来，就一个类，直接copy到你项目就行了。

**Comment by LwkCoder** [comment]
@zhangruiyu 
implemetation 'com.lwkandroid:StateFrameLayout:last-version'
修改了引用，重新上传到jcenter了，我这边试了已经可以引用了
