### ISSUE TITLE
关于空视图多文案同布局的问题

### ISSUE THREAD

**Issue by hegelsu** [Vanish136/StateFrameLayout#2]
目前的业务是不同的界面会有不同的空提示文案，但layout的布局都是一样的，能否调整这种情况来减少layout的个数？

**Comment by LwkCoder** [comment]
这很好解决啊，Activity/Fragment里引用一样的空layout文件，在对应的Activity、Fragment里find出空layout文件中的TextView设置文案即可

**Comment by hegelsu** [comment]
是的是的
